"""
Django settings for velvady project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import logging
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
from django.urls import reverse_lazy

load_dotenv()

# Secret key for stripe
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-placeholder")





LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}






# =======================================================
# BASE DIRECTORY
# =======================================================

# I am using BASE_DIR to construct full paths relative to the project root
BASE_DIR = Path(__file__).resolve().parent.parent





# =======================================================
# DEVELOPMENT MODE SETTINGS
# =======================================================

# Development settings
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['velvady-app-b7f67234cb3b.herokuapp.com', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://didactic-parakeet-v945gq97vgj2pgrg-8000.app.github.dev',
]





# =======================================================
# INSTALLED APPLICATIONS
# =======================================================

# These are the built-in Django apps and custom apps used in this project
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Custom project apps
    "core",
    "accounts",
    "products",
    'cloudinary',
    'cloudinary_storage',
]

# I am setting Django to use my custom user model from the 'accounts' app
AUTH_USER_MODEL = 'accounts.CustomUser'





# =======================================================
# MIDDLEWARE CONFIGURATION
# =======================================================

# Middleware is used to process requests globally before reaching a view
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]





# =======================================================
# URL CONFIGURATION
# =======================================================

# The root URLConf points to the top-level routing file
ROOT_URLCONF = "velvady.urls"





# =======================================================
# TEMPLATE CONFIGURATION
# =======================================================

# Django will load HTML templates from all app directoriesSECRET_KEY
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # No custom template folders needed for now
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]





# =======================================================
# WSGI CONFIGURATION
# =======================================================

# This sets the entry point for running the project via WSGI server
WSGI_APPLICATION = "velvady.wsgi.application"





# =======================================================
# DATABASE CONFIGURATION
# =======================================================

# PostSQL
DATABASES = {
    'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
}





# =======================================================
# PASSWORD VALIDATION FOR USER SECURITY
# =======================================================

# I am enforcing strong password rules for the site to meet MP4 distinction-level security expectations
# These validators ensure the password is not too short, not too common, and not entirely numeric
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},  # I have raised the minimum length to 12 characters for added security
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]





# =======================================================
# INTERNATIONALISATION SETTINGS
# =======================================================

# I am keeping default English and UTC time zone for a UK-based project
LANGUAGE_CODE = "en-us"
TIME_ZONE = 'Europe/London'
USE_I18N = True
USE_TZ = True





# =======================================================
# STATIC FILES CONFIGURATION
# =======================================================

# Static files such as CSS and JavaScript are served from this URL
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')





# =======================================================
# PRIMARY KEY FIELD TYPE
# =======================================================

# I am setting the default type for primary keys on all models
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"





# =======================================================
# SESSION SECURITY SETTINGS
# =======================================================

# I am limiting session lifetime to 30 minutes of inactivity to protect user data
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds

# This setting ensures users are logged out when they close the browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True





# =======================================================
# LOGIN / LOGOUT REDIRECTION
# =======================================================

# Redirect to dashboard after login
LOGIN_REDIRECT_URL = reverse_lazy('dashboard')

# Redirect to homepage after logout
LOGOUT_REDIRECT_URL = reverse_lazy('home')





# =======================================================
# MEDIA FILES
# =======================================================

# Static files such as CSS and JavaScript are served from this URL
STATIC_URL = '/static/'

# This defines the base URL for serving user-uploaded media
MEDIA_URL = '/media/'

# This sets the directory where uploaded files will be stored during development
MEDIA_ROOT = BASE_DIR / 'media'

# This tells Django where to find static files in development
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

# This is used only when running collectstatic for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'





# =======================================================
# STRIPE
# =======================================================

# Public key for stripe
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')

STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")





# =======================================================
# EMAIL CONFIGURATION
# =======================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER





# =======================================================
# CLOUDINARY MEDIA STORAGE
# =======================================================

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}