name: Deploy VelVady

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "**/*"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "**/*"
          target: /srv/django/apps/mp4-velvady/src/
          strip_components: 0
          overwrite: true

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            sudo sh -lc ' \
              : > /etc/velvady.env && \
              echo "DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }}" >> /etc/velvady.env && \
              echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> /etc/velvady.env && \
              echo "DEBUG=${{ secrets.DEBUG }}" >> /etc/velvady.env && \
              echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> /etc/velvady.env \
            '
            sudo chmod 600 /etc/velvady.env
            sudo chown root:root /etc/velvady.env

            source /srv/django/apps/mp4-velvady/venv/bin/activate
            pip install --upgrade pip
            pip install -r /srv/django/apps/mp4-velvady/src/requirements.txt

            cd /srv/django/apps/mp4-velvady/src
            python manage.py collectstatic --noinput
            python manage.py migrate --noinput

            sudo systemctl restart gunicorn-velvady
            sudo systemctl --no-pager status gunicorn-velvady || true
