name: Deploy VelVady

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "**/*"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            accounts/**
            core/**
            products/**
            velvady/**
            media/**
            manage.py
            requirements.txt
            Procfile
            README.md
          target: /srv/django/apps/mp4-velvady/src/
          strip_components: 0
          overwrite: true

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            # 1) Build /etc/velvady.env without heredocs
            sudo sh -lc ' \
              : > /etc/velvady.env && \
              echo "DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }}" >> /etc/velvady.env && \
              echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> /etc/velvady.env && \
              echo "DEBUG=${{ secrets.DEBUG }}" >> /etc/velvady.env && \
              echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> /etc/velvady.env && \
              echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> /etc/velvady.env && \
              echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> /etc/velvady.env && \
              echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> /etc/velvady.env && \
              echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> /etc/velvady.env && \
              echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> /etc/velvady.env && \
              echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> /etc/velvady.env && \
              echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> /etc/velvady.env && \
              echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> /etc/velvady.env \
            '
            sudo chmod 600 /etc/velvady.env
            sudo chown root:root /etc/velvady.env

            # 2) Install/upgrade deps
            source /srv/django/apps/mp4-velvady/venv/bin/activate
            pip install --upgrade pip
            pip install -r /srv/django/apps/mp4-velvady/src/requirements.txt

            # 3) Django management
            cd /srv/django/apps/mp4-velvady/src
            python manage.py collectstatic --noinput
            python manage.py migrate --noinput

            # 4) Restart app
            sudo systemctl restart gunicorn-velvady
            sudo systemctl --no-pager status gunicorn-velvady || true