# Generated by Django 5.2.1 on 2025-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("Design", "Design"),
                    ("Business", "Business"),
                    ("Tech", "Tech"),
                    ("Writing", "Writing"),
                    ("Marketing", "Marketing"),
                ],
                default="Design",
                help_text="Select a category for this service.",
                max_length=50,
            ),
        ),
    ]
