# Generated by Django 5.2.1 on 2025-06-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_service_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
