# Generated by Django 5.2.1 on 2025-06-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
